modLoader="javafml"
loaderVersion="[31,)"
issueTrackerURL="https://gitlab.com/groups/modding-legacy/-/issues"
[[mods]]
modId="good_nights_sleep"
version="${file.jarVersion}"
displayName="Good Night's Sleep"
updateJSONURL="http://changelogs.moddinglegacy.com/good-nights-sleep.json"
displayURL="https://moddinglegacy.com/"
logoFile="logo.png"
credits="tippyfoo/bob0productions for being so passonate about the mod, and allowing us to continue it!"
authors="tippyfoo, KingPhygieBoo, Silver_David, MCVinnyQ"
description='''
The Good Night's Sleep mod adds two new dimensions, the good dream and the nightmare. Each dream land is accessed through sleeping in its corresponding bed, rather than stepping through a portal.
'''
[[dependencies.good_nights_sleep]]
    modId="forge"
    mandatory=true
    versionRange="[31.2.31,)"
    ordering="NONE"
    side="BOTH"
[[dependencies.good_nights_sleep]]
    modId="minecraft"
    mandatory=true
    versionRange="[1.15.2]"
    ordering="NONE"
    side="BOTH"