modLoader="javafml"
loaderVersion="[28,)"
issueTrackerURL="https://gitlab.com/modding-legacy/Good-Night-Sleep/issues"
[[mods]]
modId="goodnightsleep"
version="${file.jarVersion}"
displayName="Good Night's Sleep"
updateJSONURL="https://gist.githubusercontent.com/Lachney/30ab83d5fe6bd534880ba6efb8f958a3/raw/good-nights-sleep-changelog.json"
displayURL="https://moddinglegacy.com/"
logoFile=""
credits="tippyfoo/bob0productions for being so passonate about the mod, and allowing us to continue it!"
authors="KingPhygieBoo, Silver_David"
description='''
The Good Night's Sleep mod adds two new dimensions, the good dream and the nightmare. Each dream land is accessed through sleeping in its corresponding bed, rather than stepping through a portal.
'''
[[dependencies.goodnightsleep]] #optional
    modId="forge"
    mandatory=true
    versionRange="[28,)"
    ordering="NONE"
    side="BOTH"
# Here's another dependency
[[dependencies.goodnightsleep]]
    modId="minecraft"
    mandatory=true
    versionRange="[1.14.4]"
    ordering="NONE"
    side="BOTH"