modLoader="javafml"
loaderVersion="[33,)"
issueTrackerURL="https://gitlab.com/groups/modding-legacy/-/issues"
license="https://www.gnu.org/licenses/gpl-3.0.en.html"
[[mods]]
modId="good_nights_sleep"
version="${file.jarVersion}"
displayName="Good Night's Sleep"
updateJSONURL="https://moddinglegacy.com/supporters-changelogs/good-nights-sleep.json"
displayURL="https://moddinglegacy.com/"
logoFile="logo.png"
credits="tippyfoo/bob0productions for being so passonate about the mod, and allowing us to continue it!"
authors="tippyfoo, KingPhygieBoo, Silver_David, MCVinnyQ"
description='''
The Good Night's Sleep mod adds two new dimensions, the good dream and the nightmare. Each dream land is accessed through sleeping in its corresponding bed, rather than stepping through a portal.
'''
[[dependencies.good_nights_sleep]]
    modId="forge"
    mandatory=true
    versionRange="[33.0.22,)"
    ordering="NONE"
    side="BOTH"
[[dependencies.good_nights_sleep]]
    modId="minecraft"
    mandatory=true
    versionRange="[1.16.2]"
    ordering="NONE"
    side="BOTH"